name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest  # Use Ubuntu runner provided by GitHub

    steps:
      # 1. Checkout the repository code
      - name: Checkout the repository
        uses: actions/checkout@v2

      # 2. Set up Node.js (use the same version as in your project)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Match this with the version you use locally

      # 3. Install dependencies
      - name: Install dependencies
        run: npm ci  # Installs dependencies from package-lock.json

      # 4. Run Cypress tests
      - name: Run Cypress tests
        run: npx cypress run  # Runs Cypress tests in headless mode

      # 5. Upload Cypress results (screenshots, videos)
      - name: Upload Cypress results
        uses: actions/upload-artifact@v2
        with:
          name: cypress-results
          path: cypress/results  # Adjust if you want to upload specific artifacts
